import {
  Geist,
  Geist_Mono,
  Lexend_Giga,
  Lexend_Zetta,
  Saira,
} from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "./globals.css";
import MainMenu from "./components/MainMenu";

config.autoAddCss = false; // do NOT add CSS to fontAwesome automatically

const lexendGiga = Lexend_Giga({
  variable: "--font-lexend-giga",
  weight: "variable",
  subsets: ["latin"],
});

const lexendZetta = Lexend_Zetta({
  variable: "--font-lexend-zetta",
  weight: "variable",
  subsets: ["latin"],
});

const saira = Saira({
  variable: "--font-saira-sans",
  weight: "variable",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lexendGiga.variable} ${lexendZetta.variable} ${saira.variable} antialiased`}
      >
        <MainMenu />
        {children}
      </body>
    </html>
  );
}
